#!@bash@/bin/bash
set -ex

VARIABLES="XDG_CURRENT_DESKTOP XDG_SESSION_TYPE"
VARIABLES="${VARIABLES} DISPLAY I3SOCK SWAYSOCK WAYLAND_DISPLAY"
VARIABLES="${VARIABLES} MOZ_ENABLE_WAYLAND SDL_VIDEODRIVER"
VARIABLES="${VARIABLES} QT_QPA_PLATFORM QT_WAYLAND_DISABLE_WINDOWDECORATION"
VARIABLES="${VARIABLES} GTK_USE_PORTAL NIXOS_XDG_OPEN_USE_PORTAL"
VARIABLES="${VARIABLES} _JAVA_AWT_WM_NONREPARENTING"
VARIABLES="${VARIABLES} GST_PLUGIN_SYSTEM_PATH_1_0 GI_TYPELIB_PATH GRL_PLUGIN_PATH"
VARIABLES="${VARIABLES} GIO_EXTRA_MODULES GDK_PIXBUF_MODULE_FILE"
VARIABLES="${VARIABLES} XCURSOR_THEME XCURSOR_SIZE"
VARIABLES="${VARIABLES} PATH"

# fcitx5
VARIABLES="${VARIABLES} XMODIFIERS QT_PLUGIN_PATH GTK_IM_MODULE QT_IM_MODULE"

export PATH=@dbus@/bin:@systemd@/bin:$PATH

# shellcheck disable=SC2086
systemctl --user import-environment $VARIABLES

# DBus activation environment is independent from systemd. While most of
# dbus-activated services are already using `SystemdService` directive, some
# still don't and thus we should set the dbus environment with a separate
# command.
# shellcheck disable=SC2086
dbus-update-activation-environment --systemd ${VARIABLES:- --all}

# dbus-send --print-reply --dest=org.freedesktop.portal.Settings /org/freedesktop/portal/Settings org.freedesktop.portal.Settings.ReadAll

echo "confirming startup of sway-gnome on $WAYLAND_DISPLAY"

export NOTIFY_SOCKET=${SWAY_NOTIFY_SOCKET}
exec systemd-notify --ready
