#!@bash@/bin/bash
set -ex

. /etc/profile

export MOZ_ENABLE_WAYLAND=1
export QT_QPA_PLATFORM="wayland;xcb"
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export GTK_USE_PORTAL=1
export NIXOS_XDG_OPEN_USE_PORTAL=1
export GNOME_SESSION_DEBUG=1
# Fix for some Java AWT applications (e.g. Android Studio),
# use this if they aren't displayed properly:
export _JAVA_AWT_WM_NONREPARENTING=1
export XDG_CURRENT_DESKTOP="sway:GNOME"
export XDG_SESSION_DESKTOP=GNOME
export XDG_SESSION_TYPE=wayland
export XCURSOR_SIZE=48
export SWAY_NOTIFY_SOCKET=${NOTIFY_SOCKET}
unset NOTIFY_SOCKET

exec @sway@/bin/sway
